[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = -ra --strict-markers --showlocals

markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow tests
    api: API tests
    db: Database tests
