"""Data models for MVP"""
from dataclasses import dataclass, asdict
from typing import List, Optional
from datetime import datetime
from decimal import Decimal
import json


@dataclass
class Position:
    """Represents a portfolio position"""
    symbol: str
    quantity: float
    avg_entry_price: float
    current_price: float
    market_value: float
    unrealized_pl: float
    unrealized_pl_pct: float
    # Original cost basis from Robinhood (for true P&L calculation)
    original_cost_basis: Optional[float] = None  # Original avg cost per share
    original_pl: Optional[float] = None  # P&L vs original cost
    original_pl_pct: Optional[float] = None  # P&L % vs original cost

    def to_dict(self):
        return asdict(self)


@dataclass
class Portfolio:
    """Represents the entire portfolio"""
    cash: float
    buying_power: float
    portfolio_value: float
    positions: List[Position]
    last_updated: datetime

    def to_dict(self):
        return {
            'cash': self.cash,
            'buying_power': self.buying_power,
            'portfolio_value': self.portfolio_value,
            'positions': [p.to_dict() for p in self.positions],
            'last_updated': self.last_updated.isoformat()
        }


@dataclass
class Recommendation:
    """Agent recommendation"""
    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    quantity: int
    conviction: int  # 0-100
    reasoning: str
    agent_id: str
    supporting_data: dict

    def to_dict(self):
        return asdict(self)


@dataclass
class AgentAnalysis:
    """Complete analysis from an agent"""
    agent_id: str
    timestamp: datetime
    recommendations: List[Recommendation]
    summary: str
    confidence: int  # 0-100

    def to_dict(self):
        return {
            'agent_id': self.agent_id,
            'timestamp': self.timestamp.isoformat(),
            'recommendations': [r.to_dict() for r in self.recommendations],
            'summary': self.summary,
            'confidence': self.confidence
        }


@dataclass
class OrchestratorReport:
    """Final recommendation report"""
    timestamp: datetime
    executive_summary: str
    recommended_actions: List[dict]
    agent_analyses: List[AgentAnalysis]
    risk_assessment: dict
    overall_confidence: int
    top_holdings: Optional[List[dict]] = None  # Top K holdings by value

    def to_markdown(self) -> str:
        """Generate markdown report"""
        md = f"""# Portfolio Recommendations - {self.timestamp.strftime('%Y-%m-%d %H:%M')}

## Executive Summary
{self.executive_summary}

## Recommended Actions

"""
        if self.recommended_actions:
            for i, action in enumerate(self.recommended_actions, 1):
                md += f"""
### {i}. {action['action'].upper()} {action['symbol']} - {action['quantity']} shares
- **Conviction**: {action['conviction']}/100
- **Reasoning**: {action['reasoning']}
- **Estimated Cost/Proceeds**: ${action.get('estimated_value', 0):,.2f}
"""
        else:
            md += "No actions recommended at this time.\n"

        # Add top holdings section
        if self.top_holdings:
            md += f"""
## Top {len(self.top_holdings)} Holdings

| Symbol | Value | % of Portfolio | P&L |
|--------|-------|----------------|-----|
"""
            for h in self.top_holdings:
                pl_str = f"${h['pl']:+,.2f} ({h['pl_pct']:+.1f}%)" if h.get('pl') is not None else "N/A"
                md += f"| {h['symbol']} | ${h['value']:,.2f} | {h['pct']:.1f}% | {pl_str} |\n"

        md += """
## Risk Assessment

"""
        for key, value in self.risk_assessment.items():
            md += f"- **{key}**: {value}\n"

        md += f"""
## Overall Confidence: {self.overall_confidence}/100

---
*Generated by Agentic Portfolio Manager MVP*
"""
        return md

    def save_to_file(self, filepath: str):
        """Save report to markdown file"""
        with open(filepath, 'w') as f:
            f.write(self.to_markdown())

    def to_dict(self):
        return {
            'timestamp': self.timestamp.isoformat(),
            'executive_summary': self.executive_summary,
            'recommended_actions': self.recommended_actions,
            'agent_analyses': [a.to_dict() for a in self.agent_analyses],
            'risk_assessment': self.risk_assessment,
            'overall_confidence': self.overall_confidence
        }


def save_json(data: dict, filepath: str):
    """Save data to JSON file"""
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2, default=str)


def load_json(filepath: str) -> dict:
    """Load data from JSON file"""
    try:
        with open(filepath, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
